name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          path: alist-web
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive


      - name: Build
        run: |
          cd alist-web
          pnpm install
          pnpm build
                  

      - name: Compress dist to ZIP and TAR.GZ
        run: |
          zip -r dist.zip dist
          tar -czf dist.tar.gz dist

      # 6. Upload dist.zip as an artifact
      - name: Upload dist.zip
        uses: actions/upload-artifact@v3
        with:
          name: dist-zip
          path: dist.zip

      # 7. Upload dist.tar.gz as an artifact
      - name: Upload dist.tar.gz
        uses: actions/upload-artifact@v3
        with:
          name: dist-tar-gz
          path: dist.tar.gz
     
